const $=selector=>document.querySelector(selector);
let csrf=sessionStorage.getItem('csrf')||'';
let devices=[];
let current=null;
let toastTimer=null;

const api=async(action,options={})=>{
 const {query,...fetchOptions}=options;
 const params=new URLSearchParams({action,...(query||{})});
 const headers={'Content-Type':'application/json',...(fetchOptions.headers||{})};
 if(csrf&&fetchOptions.method&&fetchOptions.method!=='GET')headers['X-CSRF-Token']=csrf;
 const response=await fetch(`api.php?${params}`,{credentials:'same-origin',...fetchOptions,headers});
 const data=await response.json().catch(()=>({error:'Некорректный ответ сервера'}));
 if(!response.ok)throw new Error(data.error||'Ошибка');
 return data;
};
function toast(text){const element=$('#toast');clearTimeout(toastTimer);element.textContent=text;element.classList.add('show');toastTimer=setTimeout(()=>element.classList.remove('show'),4200)}
function formData(form){return Object.fromEntries(new FormData(form))}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}

async function authenticate(){try{const me=await api('me',{method:'GET'});csrf=me.csrf;sessionStorage.setItem('csrf',csrf);await showDashboard(me.email)}catch{csrf='';sessionStorage.removeItem('csrf');showAuth()}}
function showAuth(){$('#auth').classList.remove('hidden');$('#dashboard').classList.add('hidden');$('#logout').classList.add('hidden')}
async function showDashboard(email){$('#auth').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#logout').classList.remove('hidden');$('#account').textContent=email;await loadDevices()}

let authMode='login';
function setAuthMode(mode){authMode=mode;const register=mode==='register';$('#mode-login').classList.toggle('active',!register);$('#mode-register').classList.toggle('active',register);$('#mode-login').setAttribute('aria-selected',String(!register));$('#mode-register').setAttribute('aria-selected',String(register));$('#auth-title').textContent=register?'Регистрация':'Вход';$('#auth-hint').textContent=register?'После регистрации подтвердите адрес электронной почты.':'Сессия сохранится на этом устройстве на 30 дней.';$('#password-label').textContent=register?'Пароль от 7 символов':'Пароль';$('#auth-password').minLength=register?7:0;$('#auth-password').autocomplete=register?'new-password':'current-password';$('#auth-submit').textContent=register?'Создать аккаунт':'Войти';$('#resend-verification').classList.toggle('hidden',!register)}
$('#mode-login').onclick=()=>setAuthMode('login');
$('#mode-register').onclick=()=>setAuthMode('register');
$('#auth-form').addEventListener('submit',async event=>{event.preventDefault();try{const data=await api(authMode,{method:'POST',body:JSON.stringify(formData(event.target))});if(authMode==='login'){csrf=data.csrf;sessionStorage.setItem('csrf',csrf);await showDashboard(data.email)}else{toast(data.message);event.target.reset();setAuthMode('login')}}catch(error){toast(error.message)}});
$('#resend-verification').onclick=async()=>{const email=$('#auth-form input[name="email"]').value.trim();if(!email){toast('Введите email');return}try{const data=await api('resend-verification',{method:'POST',body:JSON.stringify({email})});toast(data.message)}catch(error){toast(error.message)}};
$('#logout').addEventListener('click',async()=>{try{await api('logout',{method:'POST',body:'{}'})}catch{}csrf='';sessionStorage.removeItem('csrf');showAuth()});

async function loadDevices(){const data=await api('devices',{method:'GET'});devices=data.devices;const root=$('#device-list');root.replaceChildren();if(!devices.length){root.innerHTML='<div class="card"><h3>Устройств пока нет</h3><p>Добавьте компьютер и введите код из TimeScreen Control.</p></div>';return}devices.forEach(device=>{const online=device.last_seen_at&&data.server_time-device.last_seen_at<90;device.online=online;const card=document.createElement('article');card.className='device';const role=device.access_role==='owner'?'Владелец':'Совместный доступ';const shared=Math.max(0,(device.members||[]).length-1);card.innerHTML=`<h3>${escapeHtml(device.name)}</h3><div class="meta">${escapeHtml(device.platform)} · ${role}${shared?` · доступ ещё у ${shared}`:''}</div><p class="status ${online?'':'offline'}">${online?'В сети':'Не в сети'}</p><div class="device-actions"><button>Открыть настройки</button></div>`;card.querySelector('button').onclick=()=>openDevice(device);root.append(card)})}
$('#add-device').onclick=()=>{$('#pair-code').value='';$('#pair-dialog').showModal()};
$('#pair-submit').onclick=async()=>{try{await api('pair',{method:'POST',body:JSON.stringify({code:$('#pair-code').value})});$('#pair-dialog').close();toast('Устройство связано');await loadDevices()}catch(error){toast(error.message)}};

const dayNames=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
function intervalRow(value={start:'08:00',end:'21:00',days:[0,1,2,3,4,5,6]}){const row=document.createElement('div');row.className='interval';row.innerHTML=`<label>С<input class="start" type="time" value="${escapeHtml(value.start)}" required></label><label>До<input class="end" type="time" value="${escapeHtml(value.end)}" required></label><div class="days"></div><button type="button" class="danger" aria-label="Удалить интервал">×</button>`;const days=row.querySelector('.days');dayNames.forEach((name,index)=>{const label=document.createElement('label');label.innerHTML=`<input type="checkbox" value="${index}" ${value.days.includes(index)?'checked':''}>${name}`;days.append(label)});row.querySelector('button').onclick=()=>row.remove();return row}
$('#add-interval').onclick=()=>$('#intervals').append(intervalRow());
function formatDuration(value){const seconds=Math.max(0,Number(value)||0);if(seconds<60)return 'меньше минуты';const minutes=Math.ceil(seconds/60);if(minutes<60)return `${minutes} мин`;const hours=Math.floor(minutes/60),rest=minutes%60;return rest?`${hours} ч ${rest} мин`:`${hours} ч`}
function statusText(status){if(!status)return 'Статус обновляется';const duration=status.seconds!=null?formatDuration(status.seconds):'';if(status.state==='disabled')return 'Защита выключена';if(status.state==='uncontrolled')return 'Не контролируется';if(status.state==='break')return duration?`Перерыв · доступ через ${duration}`:'Перерыв';if(status.state==='blocked')return duration?`Заблокирован · доступ через ${duration}`:'Заблокирован';if(status.state==='allowed'&&status.next_event==='lock'&&duration)return `Разрешено · блокировка через ${duration}`;return 'Разрешено'}

async function waitForCommand(commandId,feedback,buttons,minutes){for(let attempt=0;attempt<25;attempt++){await new Promise(resolve=>setTimeout(resolve,2000));try{const result=await api('command-status',{method:'GET',query:{id:commandId}});if(result.status==='done'){feedback.textContent=`Готово: +${minutes} минут применены на компьютере`;feedback.classList.add('done');buttons.forEach(button=>button.disabled=false);await loadDevices();return}if(result.status==='expired'){feedback.textContent='Компьютер не подтвердил команду — попробуйте ещё раз';buttons.forEach(button=>button.disabled=false);return}feedback.textContent=result.status==='delivered'?'Компьютер получил команду, применяем…':'Команда отправлена, ожидаем компьютер…'}catch(error){feedback.textContent=error.message;buttons.forEach(button=>button.disabled=false);return}}feedback.textContent='Команда отправлена. Подтверждение появится после синхронизации компьютера.';buttons.forEach(button=>button.disabled=false)}
async function grantUserTime(row,username,minutes){const buttons=[...row.querySelectorAll('.user-actions button')];const feedback=row.querySelector('.command-feedback');buttons.forEach(button=>button.disabled=true);feedback.classList.remove('done');feedback.textContent='Отправляем команду…';try{const result=await api('grant-time',{method:'POST',body:JSON.stringify({device_id:current.id,username,minutes})});feedback.textContent=`+${minutes} минут поставлены в очередь`;toast(`${username}: команда отправлена на компьютер`);waitForCommand(result.command_id,feedback,buttons,minutes)}catch(error){buttons.forEach(button=>button.disabled=false);feedback.textContent=error.message;toast(error.message)}}

function renderMembers(){const root=$('#members');root.replaceChildren();(current.members||[]).forEach(member=>{const row=document.createElement('div');row.className='member';const label=member.role==='owner'?'Владелец':'Совместный доступ';row.innerHTML=`<div class="member-email">${escapeHtml(member.email)}<small>${label}</small></div>`;if(current.access_role==='owner'&&member.role!=='owner'){const remove=document.createElement('button');remove.type='button';remove.className='danger';remove.textContent='Закрыть доступ';remove.onclick=()=>removeMember(member.id);row.append(remove)}root.append(row)});$('#share-controls').classList.toggle('hidden',current.access_role!=='owner')}
async function shareDevice(){const email=$('#share-email').value.trim();if(!email){toast('Введите email второго родителя');return}const button=$('#share-device');button.disabled=true;try{const result=await api('device-share',{method:'POST',body:JSON.stringify({device_id:current.id,email})});current.members=result.members;$('#share-email').value='';renderMembers();toast(result.mail_sent?'Доступ открыт, уведомление отправлено на почту':'Доступ открыт. Почтовое уведомление отправить не удалось')}catch(error){toast(error.message)}finally{button.disabled=false}}
async function removeMember(userId){if(!confirm('Закрыть этому пользователю доступ к устройству?'))return;try{const result=await api('device-unshare',{method:'POST',body:JSON.stringify({device_id:current.id,user_id:userId})});current.members=result.members;renderMembers();toast('Доступ закрыт')}catch(error){toast(error.message)}}
$('#share-device').onclick=shareDevice;

function openDevice(device){current=device;$('#device-id').value=device.id;$('#device-title').textContent=device.name;$('#online').textContent=device.online?'Устройство в сети':'Устройство не в сети — изменения применятся после подключения';$('#online').className=device.online?'online-note':'offline-note';$('#access-role').textContent=device.access_role==='owner'?'Владелец':'Совместный доступ';const config=device.config||{enabled:false,intervals:[],controlled_users:[],show_timer:true,break_enabled:false,break_duration_minutes:10,work_duration_minutes:60};$('#enabled').checked=!!config.enabled;$('#show-timer').checked=!!config.show_timer;$('#break-enabled').checked=!!config.break_enabled;$('#work-minutes').value=config.work_duration_minutes||60;$('#break-minutes').value=config.break_duration_minutes||10;const users=$('#users');users.replaceChildren();const statuses=new Map((device.user_statuses||[]).map(row=>[row.name,row]));(device.available_users||[]).forEach(name=>{const row=document.createElement('div');row.className='user-row';const checked=(config.controlled_users||[]).includes(name);row.innerHTML=`<label class="check"><input type="checkbox" value="${escapeHtml(name)}" ${checked?'checked':''}> <span>${escapeHtml(name)}</span></label><div class="user-status"></div><div class="user-actions"><button type="button" class="secondary">+10 мин</button><button type="button" class="secondary">+30 мин</button></div><div class="command-feedback" aria-live="polite"></div>`;const status=statuses.get(name);row.querySelector('.user-status').textContent=statusText(status);if(status?.state==='blocked'||status?.state==='break')row.querySelector('.user-status').classList.add('blocked');row.querySelectorAll('.user-actions button')[0].onclick=()=>grantUserTime(row,name,10);row.querySelectorAll('.user-actions button')[1].onclick=()=>grantUserTime(row,name,30);users.append(row)});if(!device.available_users?.length)users.textContent='Список появится после синхронизации с ПК.';const intervals=$('#intervals');intervals.replaceChildren();(config.intervals||[]).forEach(value=>intervals.append(intervalRow(value)));renderMembers();$('#unlink').textContent=device.access_role==='owner'?'Отвязать устройство':'Убрать из моего списка';$('#device-dialog').showModal()}

$('#device-form').addEventListener('submit',async event=>{event.preventDefault();const intervals=[...$('#intervals').children].map(row=>({start:row.querySelector('.start').value,end:row.querySelector('.end').value,days:[...row.querySelectorAll('.days input:checked')].map(input=>Number(input.value))}));if(intervals.some(interval=>!interval.days.length)){toast('Выберите дни для каждого интервала');return}const config={enabled:$('#enabled').checked,show_timer:$('#show-timer').checked,break_enabled:$('#break-enabled').checked,work_duration_minutes:Number($('#work-minutes').value),break_duration_minutes:Number($('#break-minutes').value),controlled_users:[...$('#users').querySelectorAll('input:checked')].map(input=>input.value),intervals};try{await api('device-config',{method:'POST',body:JSON.stringify({device_id:current.id,config})});$('#device-dialog').close();toast('Настройки сохранены и отправлены на компьютер');await loadDevices()}catch(error){toast(error.message)}});
$('#unlink').onclick=async()=>{const owner=current.access_role==='owner';if(!confirm(owner?'Отвязать устройство и закрыть весь совместный доступ?':'Убрать устройство из своего списка?'))return;try{await api(owner?'unlink':'leave-device',{method:'POST',body:JSON.stringify({device_id:current.id})});$('#device-dialog').close();toast(owner?'Устройство отвязано':'Совместный доступ удалён');await loadDevices()}catch(error){toast(error.message)}};

let installPrompt=null;
const installButton=$('#install-app');
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;installButton.classList.remove('hidden')});
installButton.onclick=async()=>{if(!installPrompt)return;installButton.disabled=true;await installPrompt.prompt();const choice=await installPrompt.userChoice;if(choice.outcome==='accepted')toast('TimeScreen устанавливается на устройство');installPrompt=null;installButton.classList.add('hidden');installButton.disabled=false};
window.addEventListener('appinstalled',()=>{installPrompt=null;installButton.classList.add('hidden');toast('TimeScreen установлен')});
if(window.matchMedia('(display-mode: standalone)').matches)installButton.classList.add('hidden');
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
authenticate();
