const $=s=>document.querySelector(s); let csrf=sessionStorage.getItem('csrf')||''; let devices=[]; let current=null;
const api=async(action,options={})=>{const headers={'Content-Type':'application/json',...(options.headers||{})};if(csrf&&options.method&&options.method!=='GET')headers['X-CSRF-Token']=csrf;const r=await fetch(`api.php?action=${encodeURIComponent(action)}`,{credentials:'same-origin',...options,headers});const data=await r.json().catch(()=>({error:'Некорректный ответ сервера'}));if(!r.ok)throw new Error(data.error||'Ошибка');return data};
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3200)}
function formData(form){return Object.fromEntries(new FormData(form))}
async function authenticate(){try{const me=await api('me',{method:'GET'});csrf=me.csrf;sessionStorage.setItem('csrf',csrf);showDashboard(me.email)}catch{csrf='';sessionStorage.removeItem('csrf');showAuth()}}
function showAuth(){$('#auth').classList.remove('hidden');$('#dashboard').classList.add('hidden');$('#logout').classList.add('hidden')}
async function showDashboard(email){$('#auth').classList.add('hidden');$('#dashboard').classList.remove('hidden');$('#logout').classList.remove('hidden');$('#account').textContent=email;await loadDevices()}
let authMode='login';
function setAuthMode(mode){authMode=mode;const register=mode==='register';$('#mode-login').classList.toggle('active',!register);$('#mode-register').classList.toggle('active',register);$('#mode-login').setAttribute('aria-selected',String(!register));$('#mode-register').setAttribute('aria-selected',String(register));$('#auth-title').textContent=register?'Регистрация':'Вход';$('#auth-hint').textContent=register?'После регистрации подтвердите адрес электронной почты.':'Сессия сохранится на этом устройстве на 30 дней.';$('#password-label').textContent=register?'Пароль от 7 символов':'Пароль';$('#auth-password').minLength=register?7:0;$('#auth-password').autocomplete=register?'new-password':'current-password';$('#auth-submit').textContent=register?'Создать аккаунт':'Войти'}
$('#mode-login').onclick=()=>setAuthMode('login');$('#mode-register').onclick=()=>setAuthMode('register');
$('#auth-form').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api(authMode,{method:'POST',body:JSON.stringify(formData(e.target))});if(authMode==='login'){csrf=d.csrf;sessionStorage.setItem('csrf',csrf);await showDashboard(d.email)}else{toast(d.message);e.target.reset();setAuthMode('login')}}catch(err){toast(err.message)}});
$('#logout').addEventListener('click',async()=>{try{await api('logout',{method:'POST',body:'{}'})}catch{}csrf='';sessionStorage.removeItem('csrf');showAuth()});
async function loadDevices(){const d=await api('devices',{method:'GET'});devices=d.devices;const root=$('#device-list');root.replaceChildren();if(!devices.length){root.innerHTML='<div class="card"><h3>Устройств пока нет</h3><p>Добавьте компьютер и введите код из TimeScreen Control.</p></div>';return}devices.forEach(dev=>{const online=dev.last_seen_at&&d.server_time-dev.last_seen_at<90;const card=document.createElement('article');card.className='device';card.innerHTML=`<h3>${escapeHtml(dev.name)}</h3><div class="meta">${escapeHtml(dev.platform)}</div><p class="status ${online?'':'offline'}">${online?'В сети':'Не в сети'}</p><button>Настроить</button>`;card.querySelector('button').onclick=()=>openDevice(dev,online);root.append(card)})}
$('#add-device').onclick=()=>{$('#pair-code').value='';$('#pair-dialog').showModal()};
$('#pair-submit').onclick=async()=>{try{await api('pair',{method:'POST',body:JSON.stringify({code:$('#pair-code').value})});$('#pair-dialog').close();toast('Устройство связано');await loadDevices()}catch(err){toast(err.message)}};
const dayNames=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
function intervalRow(value={start:'08:00',end:'21:00',days:[0,1,2,3,4,5,6]}){const row=document.createElement('div');row.className='interval';row.innerHTML=`<label>С<input class="start" type="time" value="${value.start}" required></label><label>До<input class="end" type="time" value="${value.end}" required></label><div class="days"></div><button type="button" class="danger">×</button>`;const days=row.querySelector('.days');dayNames.forEach((name,i)=>{const label=document.createElement('label');label.innerHTML=`<input type="checkbox" value="${i}" ${value.days.includes(i)?'checked':''}>${name}`;days.append(label)});row.querySelector('button').onclick=()=>row.remove();return row}
$('#add-interval').onclick=()=>$('#intervals').append(intervalRow());
function openDevice(dev,online){current=dev;$('#device-id').value=dev.id;$('#device-title').textContent=dev.name;$('#online').textContent=online?'Устройство в сети':'Устройство не в сети — изменения применятся после подключения';const c=dev.config||{enabled:false,intervals:[],controlled_users:[],show_timer:true,break_enabled:false,break_duration_minutes:10,work_duration_minutes:60};$('#enabled').checked=!!c.enabled;$('#show-timer').checked=!!c.show_timer;$('#break-enabled').checked=!!c.break_enabled;$('#work-minutes').value=c.work_duration_minutes||60;$('#break-minutes').value=c.break_duration_minutes||10;const users=$('#users');users.replaceChildren();(dev.available_users||[]).forEach(name=>{const label=document.createElement('label');label.className='check';const checked=(c.controlled_users||[]).includes(name);label.innerHTML=`<input type="checkbox" value="${escapeHtml(name)}" ${checked?'checked':''}> ${escapeHtml(name)}`;users.append(label)});if(!dev.available_users?.length)users.textContent='Список появится после синхронизации с ПК.';const ints=$('#intervals');ints.replaceChildren();(c.intervals||[]).forEach(v=>ints.append(intervalRow(v)));$('#device-dialog').showModal()}
$('#device-form').addEventListener('submit',async e=>{e.preventDefault();const intervals=[...$('#intervals').children].map(row=>({start:row.querySelector('.start').value,end:row.querySelector('.end').value,days:[...row.querySelectorAll('.days input:checked')].map(i=>Number(i.value))}));if(intervals.some(i=>!i.days.length)){toast('Выберите дни для каждого интервала');return}const config={enabled:$('#enabled').checked,show_timer:$('#show-timer').checked,break_enabled:$('#break-enabled').checked,work_duration_minutes:Number($('#work-minutes').value),break_duration_minutes:Number($('#break-minutes').value),controlled_users:[...$('#users').querySelectorAll('input:checked')].map(i=>i.value),intervals};try{await api('device-config',{method:'POST',body:JSON.stringify({device_id:current.id,config})});$('#device-dialog').close();toast('Настройки сохранены');await loadDevices()}catch(err){toast(err.message)}});
document.querySelectorAll('.grant').forEach(btn=>btn.onclick=async()=>{try{await api('grant-time',{method:'POST',body:JSON.stringify({device_id:current.id,minutes:Number(btn.dataset.minutes)})});toast(`Добавлено ${btn.dataset.minutes} минут`)}catch(err){toast(err.message)}});
$('#unlink').onclick=async()=>{if(!confirm('Отвязать устройство от аккаунта?'))return;try{await api('unlink',{method:'POST',body:JSON.stringify({device_id:current.id})});$('#device-dialog').close();await loadDevices()}catch(err){toast(err.message)}};
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js'); authenticate();
